{% set name = "napari-compressed-labels-io" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-compressed-labels-io-{{ version }}.tar.gz
  sha256: be1d70b163a1928090d345190709ca9a2e4a3cdb33fa5d48625988ee411e61bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dask-core
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >={{ python_min }}
    - zarr

test:
  imports:
    - napari_compressed_labels_io
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DragaDoncila/napari-compressed-labels-io
  summary: Plugin exploring different options for reading and writing compressed and portable labels layers in napari.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - DragaDoncila
